Supported_Plugins: #if the plugin is supported, add it below to apply the boost.
  - "DeluxeSellwands"
  - "WildTools"
  - "Sellwand"
  - "RivalPickaxes"
  - "RivalMobSwords"
  - "RivalHarvesterHoes"
  - "RivalFishingRods"
  - "ShopGUIPlus"
  - "EconomyShopGUI"
  - "EconomyShopGUI-Premium"
  - "ManifestCollector"
  - "ZithiumCollectors"
  - "VoidChest"